services:
  - type: web
    name: freelancehub-backend
    env: node
    buildCommand: npm install --prefix server
    startCommand: node server/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
